import sqlite3
import subprocess
import os

DB_PATH = "audit_ledger.db"
TEX_PATH = "abstract_544_audit_report.tex"

def escape_latex(text):
    if text is None:
        return ""
    return (str(text)
            .replace("\\", "\\textbackslash ")
            .replace("_", "\\_")
            .replace("&", "\\&")
            .replace("#", "\\#")
            .replace("%", "\\%")
            .replace("$", "\\$"))

def generate_latex():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute("SELECT COUNT(*) FROM epa_audit_ledger;")
    total_records = cursor.fetchone()[0]
    
    cursor.execute("SELECT program_system, COUNT(*) FROM epa_audit_ledger GROUP BY program_system;")
    program_counts = cursor.fetchall()
    
    cursor.execute("SELECT frs_id, facility_name, program_system, compliance_status, record_hash FROM epa_audit_ledger;")
    records = cursor.fetchall()
    
    conn.close()
    
    latex_content = r"""\documentclass[11pt,letterpaper]{article}
\usepackage[margin=1in]{geometry}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{hyperref}
\usepackage{fancyhdr}

\pagestyle{fancy}
\setlength{\headheight}{14pt}
\fancyhf{}
\lhead{CivicAdvocate.OS | Forensic Audit Report}
\rhead{Abstract 544, Johnson County, TX}
\cfoot{\thepage}

\title{\textbf{Abstract 544 Environmental Compliance \& Forensic Audit Report}}
\author{CivicAdvocate.OS Automated Ledger System}
\date{\today}

\begin{document}

\maketitle

\section{Executive Summary}
This document constitutes an immutable cryptographic audit report generated by \textbf{CivicAdvocate.OS}. It details the spatial intersection and compliance status of United States Environmental Protection Agency (EPA) Enforcement and Compliance History Online (ECHO) records within \textbf{Abstract 544, Johnson County, Texas}. A total of \textbf{""" + str(total_records) + r"""} regulated facilities across Clean Water Act (CWA) and Resource Conservation and Recovery Act (RCRA) jurisdictions have been cataloged and anchored with SHA-512 cryptographic state digests.

\section{Jurisdictional Breakdown}
\begin{itemize}
"""
    for prog, count in program_counts:
        prog_escaped = escape_latex(prog)
        latex_content += f"    \\item \\textbf{{{prog_escaped}}}: {count} facilities\n"
        
    latex_content += r"""\end{itemize}

\section{Immutable Ledger Entries}
The following table records the verified EPA facility registrations, program systems, and truncated SHA-512 cryptographic ledger hashes corresponding to the Abstract 544 spatial audit boundary.

\begin{longtable}{p{2.2cm} p{5.5cm} p{2.2cm} p{4.5cm}}
\toprule
\textbf{FRS ID} & \textbf{Facility Name} & \textbf{Program} & \textbf{SHA-512 Digest (Prefix)} \\
\midrule
\endhead
\bottomrule
\endfoot
"""

    for r in records:
        frs_id = escape_latex(r[0])
        name = escape_latex(r[1])
        prog = escape_latex(r[2])
        h_prefix = str(r[4])[:24] + "..." if r[4] else ""
        latex_content += f"{frs_id} & {name} & {prog} & \\texttt{{{h_prefix}}} \\\\\n"

    latex_content += r"""
\end{longtable}

\section{Cryptographic Integrity Statement}
All records listed herein have been extracted, spatially joined, and sealed in \texttt{audit\_ledger.db}. State verification can be executed at any time via the CivicAdvocate.OS background verification daemons.

\end{document}
"""

    with open(TEX_PATH, "w", encoding="utf-8") as f:
        f.write(latex_content)
    print(f"Successfully generated {TEX_PATH}")

if __name__ == "__main__":
    generate_latex()
    print("Compiling PDF via pdflatex...")
    subprocess.run(["pdflatex", TEX_PATH], check=True)
    subprocess.run(["pdflatex", TEX_PATH], check=True)
    print("Compilation complete: abstract_544_audit_report.pdf generated successfully.")
