org.gradle.configuration-cache=false
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx1024m -Djava.net.preferIPv4Stack=true
android.aapt2FromMaven=false
systemProp.org.gradle.internal.http.connectionTimeout=600000
systemProp.org.gradle.internal.http.socketTimeout=600000
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
